format_version: 3
pipelines:
  pipeline-1:
    group: my-first-pipeline
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/srilakshmikelly/srilu.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - test-report:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-unit-tests:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - build.xml
                command: run
                run_if: passed
